/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QualifyRouteImport } from './routes/qualify'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as CheckRouteImport } from './routes/check'
import { Route as IndexRouteImport } from './routes/index'

const QualifyRoute = QualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/intake': typeof IntakeRoute
  '/qualify': typeof QualifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/intake': typeof IntakeRoute
  '/qualify': typeof QualifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/intake': typeof IntakeRoute
  '/qualify': typeof QualifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check' | '/intake' | '/qualify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check' | '/intake' | '/qualify'
  id: '__root__' | '/' | '/check' | '/intake' | '/qualify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  IntakeRoute: typeof IntakeRoute
  QualifyRoute: typeof QualifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qualify': {
      id: '/qualify'
      path: '/qualify'
      fullPath: '/qualify'
      preLoaderRoute: typeof QualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CheckRoute: CheckRoute,
  IntakeRoute: IntakeRoute,
  QualifyRoute: QualifyRoute,
  IndexRoute: IndexRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
